[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
kotlinxCoroutinesCore = "1.7.30"
lifecycleViewModelKtx = "2.8.7"
retrofit = "2.9.0"
roomRuntime = "2.6.1"
picasso = "2.71828"
datastorePreferences = "1.1.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-lifecycle-viewmodel-ktx = { module= "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx"}
androidx-lifecycle-livedata-ktx = { module= "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewModelKtx"}
androidx-room-compiler = {module = "androidx.room:room-compiler", version.ref = "roomRuntime"}
androidx-room-ktx = {module = "androidx.room:room-ktx", version.ref = "roomRuntime"}
androidx-room-runtime = {module = "androidx.room:room-runtime", version.ref = "roomRuntime"}
converter-gson = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
kotlinx-coroutines-android = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore"}
kotlinx-coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore"}
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
picasso = {module = "com.squareup.picasso:picasso", version.ref = "picasso"}
androidx-datastore-preferences = {module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

